### ISSUE TITLE
missing xml file

### ISSUE THREAD

**Issue by bernt-matthias** [iracooke/proteomics-datatypes#6]
During startup of our galaxy instance (dev branch) we see the following error:

```
galaxy.datatypes.registry ERROR 2017-08-31 12:44:32,820 Error loading display application (/gpfs1/data/galaxy_server/galaxy-dev/shed_tools/testtoolshed.g2.bx.psu.edu/repos/iracooke/proteomics_datatypes/349af9298
ff1/proteomics_datatypes/display_applications/proteomics/protvis_mzml.xml)
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/datatypes/registry.py", line 594, in load_display_applications
    display_app = DisplayApplication.from_file( config_path, app )
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/datatypes/display_applications/application.py", line 255, in from_file
    return cls.from_elem( parse_xml( filename ).getroot(), app, filename=filename )
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/util/__init__.py", line 214, in parse_xml
    root = tree.parse( fname, parser=ElementTree.XMLParser( target=DoctypeSafeCallbackTarget() ) )
  File "/global/apps/bioinf/galaxy/bin/Python-2.7.13/lib/python2.7/xml/etree/ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: '/gpfs1/data/galaxy_server/galaxy-dev/shed_tools/testtoolshed.g2.bx.psu.edu/repos/iracooke/proteomics_datatypes/349af9298ff1/proteomics_datatypes/display_application
s/proteomics/protvis_mzml.xml'

```

**Comment by iracooke** [comment]
Hi Bernt

Are you sure you need the proteomics_datatypes package?  Most of the datatypes should now be in the core of galaxy?

**Comment by bernt-matthias** [comment]
The openms suite lists it as a dependency: 

https://github.com/galaxyproteomics/tools-galaxyp/blob/master/tools/openms/repository_dependencies.xml

**Comment by iracooke** [comment]
@bernt-matthias I've raised this as an issue with openms as the best solution would be to remove the dependency from that repo.

https://github.com/galaxyproteomics/tools-galaxyp/issues/195

**Comment by bgruening** [comment]
I removed the file from openms!

**Comment by iracooke** [comment]
@bgruening Thanks!
